stages:
  fetch_data:
    cmd: python fetch_api.py
    deps:
      - fetch_api.py
    outs:
      - data/pic-journalier-consommation-brute.csv

  process_data:
    cmd: python process_data.py
    deps:
      - process_data.py
      - data/pic-journalier-consommation-brute.csv
    params:
      - preprocessing.lags_jours
      - preprocessing.fenetre_moyenne_mobile
    outs:
      - train_data/train.csv
      - train_data/test.csv

  train_xgb:
    cmd: python train_xgb.py
    deps:
      - train_data/train.csv
      - train_xgb.py
    params:
      - xgboost_training

  train_lgbm:
    cmd: python train_lightgbm.py
    deps:
      - train_data/train.csv
      - train_lightgbm.py
    params:
      - lightgbm_training