name: Wake up Streamlit App

on:
  schedule:
    - cron: '0 8 */1 * *'
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium
          # Installe le driver Chrome pour Ubuntu
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver

      - name: Run ping script
        run: ping_streamlit.py